### PR TITLE
bump pkgrel and add LIVEPATCH config

### PR DESCRIPTION
**Pull request by oberon-manjaro**

### CODE REVIEW

**Comment by budimanjojo** [comment]
You shouldn't include the .config here, it will be overwritten when building. Also, you don't need the line # CONFIG_LIVEPATCH is not set. It will confused the make whether to include it or not, because that line will be recognized as "use the default value", and you already put in CONFIG_LIVEPATCH=y ☺

**Comment by oberon-manjaro** [comment]
The **.config** is in a place where it's not read during build. It was just for your information. Of course we can remove it again.
When the line `CONFIG_LIVEPATCH is not set` is not included, make will still ask for it. So I had to add it.

**Comment by budimanjojo** [comment]
No, it won't ask again because you already put in CONFIG_LIVEPATCH=y. No problem though ☺

**Comment by oberon-manjaro** [comment]
I'd swear it did :smile: Cannot try it while the kernel is building now but will verify afterwards :stuck_out_tongue_winking_eye:

**Comment by budimanjojo** [comment]
Okay, we're gonna get another new release today? :smile:

**Comment by oberon-manjaro** [comment]
hopefully :yum:

**Comment by oberon-manjaro** [comment]
So. Removed `# CONFIG_LIVEPATCH is not set`
and there we go again:
`Kernel Live Patching (LIVEPATCH) [N/y/?] (NEW)`
:joy:
We're gonna keep that line! :smile:

**Comment by budimanjojo** [comment]
Oh, I misread the line above it, it's CONFIG_HAVE_LIVEPATCH instead of CONFIG_LIVEPATCH 😂
But CONFIG_HAVE_LIVEPATCH is already there inside config.x86_64, so I think we don't need to rewrite it there, because it's defaulted to be only for 64bit machine. So if we're building 32bit kernel, that config doesn't exist. 😂

**Comment by budimanjojo** [comment]
But we don't have any plan on supporting 32bit system, do we?

**Comment by oberon-manjaro** [comment]
Believe me, it does ask when you remove the line. Try it! :smile: I did already :wink:
Not sure about i686 ... I don't think it is needed.

**Comment by budimanjojo** [comment]
Yeah, I know about that. What I mean is CONFIG_LIVEPATCH is a new option that should be added, but CONFIG_HAVE_LIVEPATCH is old and it's already inside config.x86_64 so we don't need that line ☺
Okay, have you tested this kernel with latencytop from AUR? CONFIG_LATENCYTOP that I added in the PKGBUILD is to enable that option. But I don't know what do half of the outputs mean. 😢

**Pull request merged**
